<?php

namespace component\controller;

use component\controller\CommonController;
use abp\component\Api;
use abp\core\Request;
/**
 * Class ApiController
 * @package component
 */
class ApiController extends CommonController
{
    public function beforeAction(): bool
    {
        if(!Request::isPost()) {
            Api::message(true, 'Method Not Allowed. This URL can only handle the following request methods: ' . Api::supportMethod());
        }
        return parent::beforeAction(); // TODO: Change the autogenerated stub
    }
}