<?php

namespace component\controller;

use abp\core\Controller;
use model\User;

/**
 * Class СommonController
 * @package component
 *
 * @property User $user
 */
class CommonController extends Controller
{
    public $user = null;

    public function beforeAction(): bool
    {
        return parent::beforeAction(); // TODO: Change the autogenerated stub
    }

    /**
     * @param null $userId
     * @return bool|User
     */
    protected function _getUser($userId = null)
    {
        return false;
    }
}