<?php

namespace component\controller;

use abp\core\Controller;
use model\User;

/**
 * Class СommonController
 * @package component
 *
 * @property User $user
 */
class CommonController extends Controller
{
    public $user = null;

    public function beforeAction(): bool
    {
        return parent::beforeAction(); // TODO: Change the autogenerated stub
    }

    /**
     * @param null $userId
     * @return bool|User
     */
    protected function _getUser($userId = null)
    {
        $user = new User();
        $user->username = 'test';
        $user->save();
        if ($userId !== null) {
            return User::find()->byId($userId)->one();
        }
        if ($this->user === null) {
            $user = User::this();
            if (!$user) {
                return false;
            }
            $this->user = $user;
        }

        return $this->user;
    }
}