<?php

namespace component\controller;

use abp\core\Controller;
use model\User;

/**
 * Class СommonController
 * @package component
 *
 * @property User $user
 */
class CommonController extends Controller
{
    private $user = null;

    public function beforeAction(): bool
    {
        return parent::beforeAction(); // TODO: Change the autogenerated stub
    }

    protected function getUser(): ?User
    {
        if ($this->user === null) {
            if (\Abp::$user->isGuest()) {
                return null;
            }
            $this->user = User::find()->byId(\Abp::$user->getId())->active()->one();
        }
        return $this->user;
    }
}