<?php

namespace api\controller;

use abp\component\Api;
use abp\core\Request;
use component\controller\ApiController;
use component\exception\NotAuthException;
use component\exception\UserException;

class TemplateController extends ApiController
{
    /**
     * @return bool
     * @throws NotAuthException
     */
    public function beforeAction()
    {
        if (!$this->_getUser()) {
            throw new NotAuthException();
        }
        return parent::beforeAction(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function indexAction()
    {
        $user = $this->_getUser();
        try {
            $message = $user->apiResponse(Request::post());
            Api::message(false, $message);
        } catch (UserException $e) {
            Api::message(true, $e->getMessage());
        } catch (\Exception $e) {
            Api::message(true, 'Неизвестная ошибка.');
        }
    }
}