<?php
namespace console\model\query;

Use abp\database\ActiveQuery;

/**
 * Class Migrate
 * @package console\model\query
 */
class Migrate extends ActiveQuery
{
    /**
     * @param int $id
     * @return $this
     */
    public function byId($id)
    {
        return $this->where('migrate_id', $id);
    }

    /**
     * @return \console\model\Migrate
     */
    public function one()
    {
        return parent::one(); // TODO: Change the autogenerated stub
    }

    /**
     * @return \console\model\Migrate[]
     */
    public function all()
    {
        return parent::all(); // TODO: Change the autogenerated stub
    }
}