<?php

namespace controller;

use component\controller\CommonController;
use abp\exception\UserException;
use component\form\Login;
use component\form\Reg;
use Abp;

class SiteController extends CommonController
{
    /**
     * @return bool
     */
    public function beforeAction(): bool
    {
        if ($this->action == 'logout') {
            return parent::beforeAction(); // TODO: Change the autogenerated stub
        }
        if ($this->getUser()) {
            $this->redirect('profile');
        }
        return parent::beforeAction(); // TODO: Change the autogenerated stub
    }

    public function loginAction()
    {
        $this->title = 'Авторизация';
        $form = new Login();

        try {
            if ($form->validate(Abp::post())) {
                if ($form->execute()) {
                    $this->redirect('');
                }
                throw new UserException('Неверный логин или пароль');
            }
        } catch (UserException $e) {
            $this->addError($e->getMessage());
        } catch (\Throwable $t) {
            $this->addError();
        }

        $this->render([
            'user' => null,
            'form' => $form,
        ]);
    }

    public function regAction(array $param = [])
    {
        $this->title = 'Регистрация';
        $form = new Reg();

        try {
            if ($form->validate(Abp::post())) {
                if ($form->execute()) {
                    $this->redirect('');
                }
            }
        } catch (UserException $e) {
            $this->addError($e->getMessage());
        } catch (\Throwable $e) {
            $this->addError('Неизвестная ошибка.');
        }

        $this->render([
            'user' => null,
            'form' => $form,
        ]);
    }

    public function logoutAction()
    {
        Abp::$user->logoutCookie();
        $this->redirect();
    }
}