<?php
namespace model\query;

Use abp\database\ActiveQuery;

class User extends ActiveQuery
{
    /**
     * @param int $id
     * @return $this
     */
    public function byId($id)
    {
        return $this->where('user_id', $id);
    }

    /**
     * @param string $username
     * @return $this
     */
    public function byUsername($username)
    {
        return $this->where('username', $username);
    }

    /**
     * @param string $hash
     * @return $this
     */
    public function byhash($hash)
    {
        return $this->where('hash', $hash);
    }

    /**
     * @return \model\User
     */
    public function one()
    {
        return parent::one(); // TODO: Change the autogenerated stub
    }

    /**
     * @return \model\User[]
     */
    public function all()
    {
        return parent::all(); // TODO: Change the autogenerated stub
    }
}