<?php
namespace model\query;

Use abp\database\ActiveQuery;

/**
 * Class UserIp
 * @package model\query
 */
class UserIp extends ActiveQuery
{
    public function byId(string $id): self
    {
        return $this->where('user_ip_id', $id);
    }

    public function byUniqueKey(\model\User $user, string $ip): self
    {
        return $this->whereContidion([
            ['user_id' => $user->user_id],
            'and',
            ['ip' => $ip],
        ]);
    }

    /**
     * @return \model\UserIp
     */
    public function one()
    {
        return parent::one(); // TODO: Change the autogenerated stub
    }

    /**
     * @return \model\UserIp[]
     */
    public function all()
    {
        return parent::all(); // TODO: Change the autogenerated stub
    }
}