<?php
namespace model\query;

Use abp\database\ActiveQuery;

class User extends ActiveQuery
{
    public function byId(string $id): self
    {
        return $this->where('user_id', $id);
    }

    public function byUsername(string $username): self
    {
        return $this->where('username', $username);
    }

    public function byEmail(string $email): self
    {
        return $this->where('email', $email);
    }


    public function byhash(string $hash): self
    {
        return $this->where('hash', $hash);
    }

    /**
     * @return \model\User
     */
    public function one()
    {
        return parent::one(); // TODO: Change the autogenerated stub
    }

    /**
     * @return \model\User[]
     */
    public function all()
    {
        return parent::all(); // TODO: Change the autogenerated stub
    }
}