<?php
namespace model\query;

Use abp\database\ActiveQuery;

class User extends ActiveQuery
{
    public function byId(string $id): self
    {
        return $this->where(['user_id' => $id]);
    }

    public function byUsername(string $username): self
    {
        return $this->where(['username' => $username]);
    }

    public function byEmail(string $email): self
    {
        return $this->where(['email' => $email]);
    }

    public function byUserNameOrEmail(string $username): self
    {
        return $this->whereContidion([
            ['username' => $username],
            'or',
            ['email' => $username],
        ]);
    }

    public function byHash(string $hash): self
    {
        return $this->where(['hash' => $hash]);
    }

    public function active(): self
    {
        return $this->where(['is_active' => true]);
    }

    /**
     * @return \model\User
     */
    public function one()
    {
        return parent::one(); // TODO: Change the autogenerated stub
    }

    /**
     * @return \model\User[]
     */
    public function all()
    {
        return parent::all(); // TODO: Change the autogenerated stub
    }
}