<?php
namespace model\query;

Use abp\database\ActiveQuery;

/**
 * Class UserIp
 * @package model\query
 */
class UserIp extends ActiveQuery
{
    public function byId(string $id): self
    {
        return $this->where('user_ip_id', $id);
    }

    /**
     * @return \model\UserIp
     */
    public function one()
    {
        return parent::one(); // TODO: Change the autogenerated stub
    }

    /**
     * @return \model\UserIp[]
     */
    public function all()
    {
        return parent::all(); // TODO: Change the autogenerated stub
    }
}